"""
Session save/resume — Markdown-based session persistence.

Exports session state to a human-readable markdown file that users can
download and later upload to resume their advising session. No server
storage needed — the user holds the file.
"""

from __future__ import annotations

import re
from datetime import datetime


def serialize_session(org_profile: dict, messages: list[dict]) -> str:
    """Serialize org profile and conversation history to a markdown string."""
    lines = []
    lines.append("# MTM Nonprofit Tech Advisory Team — Saved Session")
    lines.append("")
    lines.append(f"*Saved on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}*")
    lines.append("")

    # Organization profile
    lines.append("## Organization Profile")
    lines.append("")

    field_labels = {
        "org_name": "Organization Name",
        "budget_tier": "Annual Budget",
        "staff_count": "Staff Count",
        "cause_area": "Cause Area",
        "current_tech": "Current Tech",
        "pain_points": "Pain Points",
        "it_capacity": "IT Support",
    }

    for key, label in field_labels.items():
        value = org_profile.get(key, "")
        if value:
            lines.append(f"- **{label}**: {value}")

    lines.append("")

    # Conversation
    lines.append("## Conversation")
    lines.append("")

    for msg in messages:
        role = msg["role"]
        content = msg["content"]

        if role == "user":
            lines.append("### User")
        else:
            lines.append("### Advisor")

        lines.append("")
        lines.append(content)
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(
        "*This file was generated by the MTM Nonprofit Technology Advisory Team. "
        "Upload it to resume your session at any time.*"
    )

    return "\n".join(lines)


def parse_session(markdown_text: str) -> tuple[dict, list[dict]]:
    """
    Parse a saved session markdown file back into org profile and messages.

    Returns:
        (org_profile, messages) — profile dict and list of role/content dicts
    """
    org_profile = {}
    messages = []

    # Parse organization profile
    label_to_key = {
        "Organization Name": "org_name",
        "Annual Budget": "budget_tier",
        "Staff Count": "staff_count",
        "Cause Area": "cause_area",
        "Current Tech": "current_tech",
        "Pain Points": "pain_points",
        "IT Support": "it_capacity",
    }

    profile_match = re.search(
        r"## Organization Profile\s*\n(.*?)(?=\n## )", markdown_text, re.DOTALL
    )
    if profile_match:
        profile_block = profile_match.group(1)
        for line in profile_block.strip().split("\n"):
            m = re.match(r"- \*\*(.+?)\*\*:\s*(.+)", line.strip())
            if m:
                label, value = m.group(1), m.group(2).strip()
                key = label_to_key.get(label)
                if key:
                    org_profile[key] = value

    # Parse conversation
    conversation_match = re.search(
        r"## Conversation\s*\n(.*?)(?=\n---|\Z)", markdown_text, re.DOTALL
    )
    if conversation_match:
        conversation_block = conversation_match.group(1)

        # Split on ### User or ### Advisor headers (handle start of block too)
        parts = re.split(r"(?:^|\n)### (User|Advisor)\s*\n", conversation_block)

        # parts[0] is text before first header (usually empty)
        # then alternating: role, content, role, content, ...
        i = 1
        while i < len(parts) - 1:
            role_label = parts[i].strip()
            content = parts[i + 1].strip()

            role = "user" if role_label == "User" else "assistant"
            if content:
                messages.append({"role": role, "content": content})

            i += 2

    return org_profile, messages
